env:
  browser: true
  node: true
  mocha: true

plugins:
  - prettier

extends:
  - airbnb
  - prettier


# parserOptions:
#   ecmaVersion: 6
#   sourceType: module
#   ecmaFeatures:
#     jsx: true

rules:
  react/jsx-filename-extension: 0
  no-var: 0
  global-require: 0
  react/prop-types: 0
  no-underscore-dangle: 0
  prefer-rest-params: 0
  no-param-reassign: 0
  no-unused-expressions: 0
  class-methods-use-this: 0
  no-plusplus: 0
  prefer-const: 0
  react/sort-comp: 0
  func-names: 0
  prefer-destructuring: 0
  consistent-return: 0
  no-useless-escape: 0
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/label-has-for: 0
  import/extensions: 0
